### ISSUE TITLE
PHP8.0

### ISSUE THREAD

**Issue by molony-cua** [LincolnUniLTL/rss2oai#1]
There is a compatibility issue between this and PHP8.0.  I am unsure if any of the original authors are willing to update, but I thought I would check

**Comment by deborahfitchett** [comment]
Hi, thanks for noting that! We've recently migrated our previously-Wordpress site to another system so unfortunately won't be able to keep this updated. I'm also very unfamiliar with PHP 8.x but scanning through a list of changes in it, I can see several that might be causing issues, so, um, if anyone does want to update it I wish them the best... :-/   I'll update the README to make this clear.

**Comment by molony-cua** [comment]
Thanks for the response.  I appreciate it.  I will look into working on this myself.  If I find a fix, I can add a pull request since the top results for OAI for Wordpress list this as the option (if you would like).

**Comment by deborahfitchett** [comment]
That would be awesome, thank you!

**Comment by molony-cua** [comment]
I have submitted a pull request.
